package com.simon.vpohode.Managers;

import com.simon.vpohode.R;

public enum ColorList {
    White("#FFFFFF", R.string.White),
    Ivory("#FFFFF0",R.string.Ivory),
    LightYellow("#FFFFE0",R.string.LightYellow),
    Yellow("#FFFF00",R.string.Yellow),
    Snow("#FFFAFA",R.string.Snow),
    FloralWhite("#FFFAF0",R.string.FloralWhite),
    LemonChiffon("#FFFACD",R.string.LemonChiffon),
    Cornsilk("#FFF8DC",R.string.Cornsilk),
    Seashell("#FFF5EE",R.string.Seashell),
    LavenderBlush("#FFF0F5",R.string.LavenderBlush),
    PapayaWhip("#FFEFD5",R.string.PapayaWhip),
    BlanchedAlmond("#FFEBCD",R.string.BlanchedAlmond),
    MistyRose("#FFE4E1",R.string.MistyRose),
    Bisque("#FFE4C4",R.string.Bisque),
    Moccasin("#FFE4B5",R.string.Moccasin),
    NavajoWhite("#FFDEAD",R.string.NavajoWhite),
    PeachPuff("#FFDAB9",R.string.PeachPuff),
    Gold("#FFD700",R.string.Gold),
    Pink("#FFC0CB",R.string.Pink),
    LightPink("#FFB6C1",R.string.LightPink),
    Orange("#FFA500",R.string.Orange),
    LightSalmon("#FFA07A",R.string.LightSalmon),
    DarkOrange("#FF8C00",R.string.DarkOrange),
    Coral("#FF7F50",R.string.Coral),
    HotPink("#FF69B4",R.string.HotPink),
    Tomato("#FF6347",R.string.Tomato),
    OrangeRed("#FF4500",R.string.OrangeRed),
    DeepPink("#FF1493",R.string.DeepPink),
    Fuchsia("#FF00FF",R.string.Fuchsia),
    Magenta("#FF00FF",R.string.Magenta),
    Red("#FF0000",R.string.Red),
    OldLace("#FDF5E6",R.string.OldLace),
    LightGoldenrodYellow("#FAFAD2",R.string.LightGoldenrodYellow),
    Linen("#FAF0E6",R.string.Linen),
    AntiqueWhite("#FAEBD7",R.string.AntiqueWhite),
    Salmon("#FA8072",R.string.Salmon),
    GhostWhite("#F8F8FF",R.string.GhostWhite),
    MintCream("#F5FFFA",R.string.MintCream),
    WhiteSmoke("#F5F5F5",R.string.WhiteSmoke),
    Beige("#F5F5DC",R.string.Beige),
    Wheat("#F5DEB3",R.string.Wheat),
    SandyBrown("#F4A460",R.string.SandyBrown),
    Azure("#F0FFFF",R.string.Azure),
    Honeydew("#F0FFF0",R.string.Honeydew),
    AliceBlue("#F0F8FF",R.string.AliceBlue),
    Khaki("#F0E68C",R.string.Khaki),
    LightCoral("#F08080",R.string.LightCoral),
    PaleGoldenrod("#EEE8AA",R.string.PaleGoldenrod),
    Violet("#EE82EE",R.string.Violet),
    DarkSalmon("#E9967A",R.string.DarkSalmon),
    Lavender("#E6E6FA",R.string.Lavender),
    LightCyan("#E0FFFF",R.string.LightCyan),
    BurlyWood("#DEB887",R.string.BurlyWood),
    Plum("#DDA0DD",R.string.Plum),
    Gainsboro("#DCDCDC",R.string.Gainsboro),
    Crimson("#DC143C",R.string.Crimson),
    PaleVioletRed("#DB7093",R.string.PaleVioletRed),
    Goldenrod("#DAA520",R.string.Goldenrod),
    Orchid("#DA70D6",R.string.Orchid),
    Thistle("#D8BFD8",R.string.Thistle),
    LightGrey("#D3D3D3",R.string.LightGrey),
    Tan("#D2B48C",R.string.Tan),
    Chocolate("#D2691E",R.string.Chocolate),
    Peru("#CD853F",R.string.Peru),
    IndianRed("#CD5C5C",R.string.IndianRed),
    MediumVioletRed("#C71585",R.string.MediumVioletRed),
    Silver("#C0C0C0",R.string.Silver),
    DarkKhaki("#BDB76B",R.string.DarkKhaki),
    RosyBrown("#BC8F8F",R.string.RosyBrown),
    MediumOrchid("#BA55D3",R.string.MediumOrchid),
    DarkGoldenrod("#B8860B",R.string.DarkGoldenrod),
    FireBrick("#B22222",R.string.FireBrick),
    PowderBlue("#B0E0E6",R.string.PowderBlue),
    LightSteelBlue("#B0C4DE",R.string.LightSteelBlue),
    PaleTurquoise("#AFEEEE",R.string.PaleTurquoise),
    GreenYellow("#ADFF2F",R.string.GreenYellow),
    LightBlue("#ADD8E6",R.string.LightBlue),
    DarkGray("#A9A9A9",R.string.DarkGray),
    Brown("#A52A2A",R.string.Brown),
    Sienna("#A0522D",R.string.Sienna),
    YellowGreen("#9ACD32",R.string.YellowGreen),
    DarkOrchid("#9932CC",R.string.DarkOrchid),
    PaleGreen("#98FB98",R.string.PaleGreen),
    DarkViolet("#9400D3",R.string.DarkViolet),
    MediumPurple("#9370DB",R.string.MediumPurple),
    LightGreen("#90EE90",R.string.LightGreen),
    DarkSeaGreen("#8FBC8F",R.string.DarkSeaGreen),
    SaddleBrown("#8B4513",R.string.SaddleBrown),
    DarkMagenta("#8B008B",R.string.DarkMagenta),
    DarkRed("#8B0000",R.string.DarkRed),
    BlueViolet("#8A2BE2",R.string.BlueViolet),
    LightSkyBlue("#87CEFA",R.string.LightSkyBlue),
    SkyBlue("#87CEEB",R.string.SkyBlue),
    Gray("#808080",R.string.Gray),
    Olive("#808000",R.string.Olive),
    Purple("#800080",R.string.Purple),
    Maroon("#800000",R.string.Maroon),
    Aquamarine("#7FFFD4",R.string.Aquamarine),
    Chartreuse("#7FFF00",R.string.Chartreuse),
    LawnGreen("#7CFC00",R.string.LawnGreen),
    MediumSlateBlue("#7B68EE",R.string.MediumSlateBlue),
    LightSlateGray("#778899",R.string.LightSlateGray),
    SlateGray("#708090",R.string.SlateGray),
    OliveDrab("#6B8E23",R.string.OliveDrab),
    SlateBlue("#6A5ACD",R.string.SlateBlue),
    DimGray("#696969",R.string.DimGray),
    MediumAquamarine("#66CDAA",R.string.MediumAquamarine),
    CornflowerBlue("#6495ED",R.string.CornflowerBlue),
    CadetBlue("#5F9EA0",R.string.CadetBlue),
    DarkOliveGreen("#556B2F",R.string.DarkOliveGreen),
    Indigo("#4B0082",R.string.Indigo),
    MediumTurquoise("#48D1CC",R.string.MediumTurquoise),
    DarkSlateBlue("#483D8B",R.string.DarkSlateBlue),
    SteelBlue("#4682B4",R.string.SteelBlue),
    RoyalBlue("#4169E1",R.string.RoyalBlue),
    Turquoise("#40E0D0",R.string.Turquoise),
    MediumSeaGreen("#3CB371",R.string.MediumSeaGreen),
    LimeGreen("#32CD32",R.string.LimeGreen),
    DarkSlateGray("#2F4F4F",R.string.DarkSlateGray),
    SeaGreen("#2E8B57",R.string.SeaGreen),
    ForestGreen("#228B22",R.string.ForestGreen),
    LightSeaGreen("#20B2AA",R.string.LightSeaGreen),
    DodgerBlue("#1E90FF",R.string.DodgerBlue),
    MidnightBlue("#191970",R.string.MidnightBlue),
    Aqua("#00FFFF",R.string.Aqua),
    Cyan("#00FFFF",R.string.Cyan),
    SpringGreen("#00FF7F",R.string.SpringGreen),
    Lime("#00FF00",R.string.Lime),
    MediumSpringGreen("#00FA9A",R.string.MediumSpringGreen),
    DarkTurquoise("#00CED1",R.string.DarkTurquoise),
    DeepSkyBlue("#00BFFF",R.string.DeepSkyBlue),
    DarkCyan("#008B8B",R.string.DarkCyan),
    Teal("#008080",R.string.Teal),
    Green("#008000",R.string.Green),
    DarkGreen("#006400",R.string.DarkGreen),
    Blue("#0000FF",R.string.Blue),
    MediumBlue("#0000CD",R.string.MediumBlue),
    DarkBlue("#00008B",R.string.DarkBlue),
    Navy("#000080",R.string.Navy),
    Black("#000000",R.string.Black);

    private String value;
    private int resource;

    ColorList(String value, int resource){
        this.value = value;
        this.resource = resource;
    }

    public String getValue() {
        return value;
    }
    public int getResource(){
        return resource;
    }
}
