package com.simon.vpohode.managers;

import com.simon.vpohode.R;

public enum ColorList {
    WHITE("#FFFFFF", R.string.White),
    IVORY("#FFFFF0",R.string.Ivory),
    LIGHT_YELLOW("#FFFFE0",R.string.LightYellow),
    YELLOW("#FFFF00",R.string.Yellow),
    SNOW("#FFFAFA",R.string.Snow),
    FLORAL_WHITE("#FFFAF0",R.string.FloralWhite),
    LEMON_CHIFFON("#FFFACD",R.string.LemonChiffon),
    CORNSILK("#FFF8DC",R.string.Cornsilk),
    SEASHELL("#FFF5EE",R.string.Seashell),
    LAVENDER_BLUSH("#FFF0F5",R.string.LavenderBlush),
    PAPAYA_WHIP("#FFEFD5",R.string.PapayaWhip),
    BLANCHED_ALMOND("#FFEBCD",R.string.BlanchedAlmond),
    MISTY_ROSE("#FFE4E1",R.string.MistyRose),
    BISQUE("#FFE4C4",R.string.Bisque),
    MOCCASIN("#FFE4B5",R.string.Moccasin),
    NAVAJO_WHITE("#FFDEAD",R.string.NavajoWhite),
    PEACH_PUFF("#FFDAB9",R.string.PeachPuff),
    GOLD("#FFD700",R.string.Gold),
    PINK("#FFC0CB",R.string.Pink),
    LIGHT_PINK("#FFB6C1",R.string.LightPink),
    ORANGE("#FFA500",R.string.Orange),
    LIGHT_SALMON("#FFA07A",R.string.LightSalmon),
    DARK_ORANGE("#FF8C00",R.string.DarkOrange),
    CORAL("#FF7F50",R.string.Coral),
    HOT_PINK("#FF69B4",R.string.HotPink),
    TOMATO("#FF6347",R.string.Tomato),
    ORANGE_RED("#FF4500",R.string.OrangeRed),
    DEEP_PINK("#FF1493",R.string.DeepPink),
    FUCHSIA("#FF00FF",R.string.Fuchsia),
    MAGENTA("#FF00FF",R.string.Magenta),
    RED("#FF0000",R.string.Red),
    OLD_LACE("#FDF5E6",R.string.OldLace),
    LIGHT_GOLDENROD_YELLOW("#FAFAD2",R.string.LightGoldenrodYellow),
    LINEN("#FAF0E6",R.string.Linen),
    ANTIQUE_WHITE("#FAEBD7",R.string.AntiqueWhite),
    SALMON("#FA8072",R.string.Salmon),
    GHOST_WHITE("#F8F8FF",R.string.GhostWhite),
    MINT_CREAM("#F5FFFA",R.string.MintCream),
    WHITE_SMOKE("#F5F5F5",R.string.WhiteSmoke),
    BEIGE("#F5F5DC",R.string.Beige),
    WHEAT("#F5DEB3",R.string.Wheat),
    SANDY_BROWN("#F4A460",R.string.SandyBrown),
    AZURE("#F0FFFF",R.string.Azure),
    HONEYDEW("#F0FFF0",R.string.Honeydew),
    ALICE_BLUE("#F0F8FF",R.string.AliceBlue),
    KHAKI("#F0E68C",R.string.Khaki),
    LIGHT_CORAL("#F08080",R.string.LightCoral),
    PALE_GOLDENROD("#EEE8AA",R.string.PaleGoldenrod),
    VIOLET("#EE82EE",R.string.Violet),
    DARK_SALMON("#E9967A",R.string.DarkSalmon),
    LAVENDER("#E6E6FA",R.string.Lavender),
    LIGHT_CYAN("#E0FFFF",R.string.LightCyan),
    BURLY_WOOD("#DEB887",R.string.BurlyWood),
    PLUM("#DDA0DD",R.string.Plum),
    GAINSBORO("#DCDCDC",R.string.Gainsboro),
    CRIMSON("#DC143C",R.string.Crimson),
    PALE_VIOLET_RED("#DB7093",R.string.PaleVioletRed),
    GOLDENROD("#DAA520",R.string.Goldenrod),
    ORCHID("#DA70D6",R.string.Orchid),
    THISTLE("#D8BFD8",R.string.Thistle),
    LIGHT_GREY("#D3D3D3",R.string.LightGrey),
    TAN("#D2B48C",R.string.Tan),
    CHOCOLATE("#D2691E",R.string.Chocolate),
    PERU("#CD853F",R.string.Peru),
    INDIAN_RED("#CD5C5C",R.string.IndianRed),
    MEDIUM_VIOLET_RED("#C71585",R.string.MediumVioletRed),
    SILVER("#C0C0C0",R.string.Silver),
    DARK_KHAKI("#BDB76B",R.string.DarkKhaki),
    ROSY_BROWN("#BC8F8F",R.string.RosyBrown),
    MEDIUM_ORCHID("#BA55D3",R.string.MediumOrchid),
    DARK_GOLDENROD("#B8860B",R.string.DarkGoldenrod),
    FIRE_BRICK("#B22222",R.string.FireBrick),
    POWDER_BLUE("#B0E0E6",R.string.PowderBlue),
    LIGHT_STEEL_BLUE("#B0C4DE",R.string.LightSteelBlue),
    PALE_TURQUOISE("#AFEEEE",R.string.PaleTurquoise),
    GREEN_YELLOW("#ADFF2F",R.string.GreenYellow),
    LIGHT_BLUE("#ADD8E6",R.string.LightBlue),
    DARK_GRAY("#A9A9A9",R.string.DarkGray),
    BROWN("#A52A2A",R.string.Brown),
    SIENNA("#A0522D",R.string.Sienna),
    YELLOW_GREEN("#9ACD32",R.string.YellowGreen),
    DARK_ORCHID("#9932CC",R.string.DarkOrchid),
    PALE_GREEN("#98FB98",R.string.PaleGreen),
    DARK_VIOLET("#9400D3",R.string.DarkViolet),
    MEDIUM_PURPLE("#9370DB",R.string.MediumPurple),
    LIGHT_GREEN("#90EE90",R.string.LightGreen),
    DARK_SEA_GREEN("#8FBC8F",R.string.DarkSeaGreen),
    SADDLE_BROWN("#8B4513",R.string.SaddleBrown),
    DARK_MAGENTA("#8B008B",R.string.DarkMagenta),
    DARK_RED("#8B0000",R.string.DarkRed),
    BLUE_VIOLET("#8A2BE2",R.string.BlueViolet),
    LIGHT_SKY_BLUE("#87CEFA",R.string.LightSkyBlue),
    SKY_BLUE("#87CEEB",R.string.SkyBlue),
    GRAY("#808080",R.string.Gray),
    OLIVE("#808000",R.string.Olive),
    PURPLE("#800080",R.string.Purple),
    MAROON("#800000",R.string.Maroon),
    AQUAMARINE("#7FFFD4",R.string.Aquamarine),
    CHARTREUSE("#7FFF00",R.string.Chartreuse),
    LAWN_GREEN("#7CFC00",R.string.LawnGreen),
    MEDIUM_SLATE_BLUE("#7B68EE",R.string.MediumSlateBlue),
    LIGHT_SLATE_GRAY("#778899",R.string.LightSlateGray),
    SLATE_GRAY("#708090",R.string.SlateGray),
    OLIVE_DRAB("#6B8E23",R.string.OliveDrab),
    SLATE_BLUE("#6A5ACD",R.string.SlateBlue),
    DIM_GRAY("#696969",R.string.DimGray),
    MEDIUM_AQUAMARINE("#66CDAA",R.string.MediumAquamarine),
    CORNFLOWER_BLUE("#6495ED",R.string.CornflowerBlue),
    CADET_BLUE("#5F9EA0",R.string.CadetBlue),
    DARK_OLIVE_GREEN("#556B2F",R.string.DarkOliveGreen),
    INDIGO("#4B0082",R.string.Indigo),
    MEDIUM_TURQUOISE("#48D1CC",R.string.MediumTurquoise),
    DARK_SLATE_BLUE("#483D8B",R.string.DarkSlateBlue),
    STEEL_BLUE("#4682B4",R.string.SteelBlue),
    ROYAL_BLUE("#4169E1",R.string.RoyalBlue),
    TURQUOISE("#40E0D0",R.string.Turquoise),
    MEDIUM_SEA_GREEN("#3CB371",R.string.MediumSeaGreen),
    LIME_GREEN("#32CD32",R.string.LimeGreen),
    DARK_SLATE_GRAY("#2F4F4F",R.string.DarkSlateGray),
    SEA_GREEN("#2E8B57",R.string.SeaGreen),
    FOREST_GREEN("#228B22",R.string.ForestGreen),
    LIGHT_SEA_GREEN("#20B2AA",R.string.LightSeaGreen),
    DODGER_BLUE("#1E90FF",R.string.DodgerBlue),
    MIDNIGHT_BLUE("#191970",R.string.MidnightBlue),
    AQUA("#00FFFF",R.string.Aqua),
    CYAN("#00FFFF",R.string.Cyan),
    SPRING_GREEN("#00FF7F",R.string.SpringGreen),
    LIME("#00FF00",R.string.Lime),
    MEDIUM_SPRING_GREEN("#00FA9A",R.string.MediumSpringGreen),
    DARK_TURQUOISE("#00CED1",R.string.DarkTurquoise),
    DEEP_SKY_BLUE("#00BFFF",R.string.DeepSkyBlue),
    DARK_CYAN("#008B8B",R.string.DarkCyan),
    TEAL("#008080",R.string.Teal),
    GREEN("#008000",R.string.Green),
    DARK_GREEN("#006400",R.string.DarkGreen),
    BLUE("#0000FF",R.string.Blue),
    MEDIUM_BLUE("#0000CD",R.string.MediumBlue),
    DARK_BLUE("#00008B",R.string.DarkBlue),
    NAVY("#000080",R.string.Navy),
    BLACK("#000000",R.string.Black);

    private final String value;
    private final int resource;

    ColorList(String value, int resource){
        this.value = value;
        this.resource = resource;
    }

    public String getValue() {
        return value;
    }
    public int getResource(){
        return resource;
    }
}
